################################################################################
#
# libdatachannel
#
################################################################################

LIBDATACHANNEL_VERSION = v0.21.2
LIBDATACHANNEL_SITE_METHOD = git
LIBDATACHANNEL_SITE = https://github.com/paullouisageneau/libdatachannel
LIBDATACHANNEL_GIT_SUBMODULES = YES
LIBDATACHANNEL_INSTALL_STAGING = YES
LIBDATACHANNEL_LICENSE = MPL-2.0
LIBDATACHANNEL_LICENSE_FILES = LICENSE

LIBDATACHANNEL_CONF_OPTS = -DPREFER_SYSTEM_LIB=1
LIBDATACHANNEL_CONF_OPTS = -DUSE_SYSTEM_PLOG=0

ifeq ($(BR2_PACKAGE_JSON_FOR_MODERN_CPP),y)
LIBDATACHANNEL_CONF_OPTS += -DUSE_SYSTEM_JSON=1
LIBDATACHANNEL_DEPENDENCIES += json-for-modern-cpp
else
LIBDATACHANNEL_CONF_OPTS += -DUSE_SYSTEM_JSON=0
endif

ifeq ($(BR2_PACKAGE_LIBNICE),y)
LIBDATACHANNEL_CONF_OPTS += -DUSE_NICE=1
LIBDATACHANNEL_DEPENDENCIES += libnice
else
LIBDATACHANNEL_CONF_OPTS += -DUSE_NICE=0
endif

ifeq ($(BR2_PACKAGE_LIBSRTP),y)
LIBDATACHANNEL_CONF_OPTS += -DUSE_SYSTEM_SRTP=1
LIBDATACHANNEL_DEPENDENCIES += libsrtp
else
LIBDATACHANNEL_CONF_OPTS += -DUSE_SYSTEM_SRTP=0
endif

$(eval $(cmake-package))
